/**
 * DPRO 中古車買取・販売 LINE
 * STEP CAR-20 LINE連絡テンプレート・送信予定・対応履歴管理
 */
window.DPRO_CAR_CONFIG = Object.freeze({
  version: "CAR-20-COMMUNICATION-TEMPLATES-HISTORY-20260723",
  apiBase: "https://dpro-used-car-line-api.dpromstk2000.workers.dev",
  companyCode: "dpro_used_car_demo",
  liffId: "",
  defaultLineUserId: "demo_car_line_001",
  reservationDaysAhead: 60,
  slotMinutes: 30,
  maxPhotoCount: 8,
  maxPhotoSizeBytes: 5 * 1024 * 1024,
  appraisalPhotoMaxCount: 8,
  listingPhotoMaxCount: 12,
  ownerSimpleMode: true,
  ownerDetailPanel: true,
  ownerLazyRender: true,
  ownerCustomerVehicle360: true,
  ownerCustomerEdit: true,
  ownerCustomerVehicleEdit: true,
  ownerDuplicateCandidateCheck: true,
  ownerAppraisalLifecycle: true,
  ownerPurchaseContractAutocreate: true,
  ownerInventoryConversion: true,
  ownerInventoryTaskAutocreate: true,
  privateAppraisalPhotoAutoPublish: false,
  publicInventoryPageSize: 24,
  publicInventoryMaxPageSize: 48,
  publicInventoryUrlState: true,
  publicInventoryAdvancedFilters: true,
  publicVehicleShare: true,
  ownerInventoryPublishReadiness: true,
  ownerInventoryPublicPreview: true,
  ownerSalesJourney360: true,
  ownerSalesLeadEdit: true,
  ownerSalesContractAutocreate: true,
  ownerSalesNextActionTask: true,
  ownerSalesLostReason: true,
  ownerSaleContractDelivery360: true,
  ownerSaleContractEdit: true,
  ownerDeliveryTaskSync: true,
  ownerDeliveryCompletionGuard: true,
  ownerDeliveryFollowupAutocreate: true,
  ownerAftercareOverview: true,
  ownerAftercare360: true,
  ownerAftercareProfileEdit: true,
  ownerAftercarePlanSync: true,
  ownerServiceHistory: true,
  ownerReplacementProspect: true,
  memberAftercareSchedule: true,
  memberServiceHistory: true,
  ownerManagementDashboard: true,
  ownerManagementTargets: true,
  ownerInventoryTurnover: true,
  ownerGrossProfit: true,
  ownerConversionMetrics: true,
  ownerStaffPerformance: true,
  ownerCommunicationOverview: true,
  ownerCommunicationTemplates: true,
  ownerCommunicationSchedule: true,
  ownerCommunicationHistory: true,
  memberCommunicationHistory: true,
  communicationAutoSend: false,
});
