/**
 * DPRO 中古車買取・販売 LINE
 * STEP CAR-15 公開在庫カタログ・車両詳細強化
 */
window.DPRO_CAR_CONFIG = Object.freeze({
  version: "CAR-15-PUBLIC-INVENTORY-CATALOG-DETAIL-20260723",
  apiBase: "https://dpro-used-car-line-api.dpromstk2000.workers.dev",
  companyCode: "dpro_used_car_demo",
  liffId: "",
  defaultLineUserId: "demo_car_line_001",
  reservationDaysAhead: 60,
  slotMinutes: 30,
  maxPhotoCount: 8,
  maxPhotoSizeBytes: 5 * 1024 * 1024,
  appraisalPhotoMaxCount: 8,
  listingPhotoMaxCount: 12,
  ownerSimpleMode: true,
  ownerDetailPanel: true,
  ownerLazyRender: true,
  ownerCustomerVehicle360: true,
  ownerCustomerEdit: true,
  ownerCustomerVehicleEdit: true,
  ownerDuplicateCandidateCheck: true,
  ownerAppraisalLifecycle: true,
  ownerPurchaseContractAutocreate: true,
  ownerInventoryConversion: true,
  ownerInventoryTaskAutocreate: true,
  privateAppraisalPhotoAutoPublish: false,
  publicInventoryPageSize: 24,
  publicInventoryMaxPageSize: 48,
  publicInventoryUrlState: true,
  publicInventoryAdvancedFilters: true,
  publicVehicleShare: true,
  ownerInventoryPublishReadiness: true,
  ownerInventoryPublicPreview: true,
});
